openshift:
  enabled: true

appName: csc-rstudio-shiny

rstudio:
  podSecurityContext: {}
  containerSecurityContext:
    runAsUser:
    runAsGroup:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  pvc:
    mountName: rstudio-server-home
    storageSize: 5Gi
  route:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
    host: rstudio.local
  random_pw_secret_key: PASSWORD
  secret:
    USER: rstudio
    PASSWORD: '{{- include "random_pw_reusable" . -}}'

shiny:
  pvc:
    mountName: shiny-server
    storageSize: 5Gi
  route:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
    host: shiny.local

buildConfig:
  gitRepoUri: https://github.com/vvvilkki/helm-charts-vvvilkki.git
  gitBranch: main
  contextDir: charts/rstudio/source
  
